[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fredapi==0.5.0",
    "numpy==1.26.0",
    "pandas==2.2.0",
    "plotly==5.18.0",
    "requests==2.31.0",
    "streamlit==1.40.0",
]
